/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

/* route tree removed - migrated to Next App Router */

export default null;
export interface FileRoutesByTo {
  '/': typeof SearchableSplitIndexRoute
  '/NotFound': typeof NotFoundRoute
  '/about': typeof DefaultAboutRoute
  '/$itemId': typeof SearchableSplitItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_default': typeof DefaultRouteRouteWithChildren
  '/_searchable': typeof SearchableRouteRouteWithChildren
  '/NotFound': typeof NotFoundRoute
  '/_default/about': typeof DefaultAboutRoute
  '/_searchable/_split': typeof SearchableSplitRouteWithChildren
  '/_searchable/_split/$itemId': typeof SearchableSplitItemIdRoute
  '/_searchable/_split/': typeof SearchableSplitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/NotFound' | '/about' | '/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/NotFound' | '/about' | '/$itemId'
  id:
    | '__root__'
    | '/_default'
    | '/_searchable'
    | '/NotFound'
    | '/_default/about'
    | '/_searchable/_split'
    | '/_searchable/_split/$itemId'
    | '/_searchable/_split/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DefaultRouteRoute: typeof DefaultRouteRouteWithChildren
  SearchableRouteRoute: typeof SearchableRouteRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/NotFound': {
      id: '/NotFound'
      path: '/NotFound'
      fullPath: '/NotFound'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_searchable': {
      id: '/_searchable'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SearchableRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_searchable/_split': {
      id: '/_searchable/_split'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SearchableSplitRouteImport
      parentRoute: typeof SearchableRouteRoute
    }
    '/_default/about': {
      id: '/_default/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DefaultAboutRouteImport
      parentRoute: typeof DefaultRouteRoute
    }
    '/_searchable/_split/': {
      id: '/_searchable/_split/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SearchableSplitIndexRouteImport
      parentRoute: typeof SearchableSplitRoute
    }
    '/_searchable/_split/$itemId': {
      id: '/_searchable/_split/$itemId'
      path: '/$itemId'
      fullPath: '/$itemId'
      preLoaderRoute: typeof SearchableSplitItemIdRouteImport
      parentRoute: typeof SearchableSplitRoute
    }
  }
}

interface DefaultRouteRouteChildren {
  DefaultAboutRoute: typeof DefaultAboutRoute
}

const DefaultRouteRouteChildren: DefaultRouteRouteChildren = {
  DefaultAboutRoute: DefaultAboutRoute,
}

const DefaultRouteRouteWithChildren = DefaultRouteRoute._addFileChildren(
  DefaultRouteRouteChildren,
)

interface SearchableSplitRouteChildren {
  SearchableSplitItemIdRoute: typeof SearchableSplitItemIdRoute
  SearchableSplitIndexRoute: typeof SearchableSplitIndexRoute
}

const SearchableSplitRouteChildren: SearchableSplitRouteChildren = {
  SearchableSplitItemIdRoute: SearchableSplitItemIdRoute,
  SearchableSplitIndexRoute: SearchableSplitIndexRoute,
}

const SearchableSplitRouteWithChildren = SearchableSplitRoute._addFileChildren(
  SearchableSplitRouteChildren,
)

interface SearchableRouteRouteChildren {
  SearchableSplitRoute: typeof SearchableSplitRouteWithChildren
}

const SearchableRouteRouteChildren: SearchableRouteRouteChildren = {
  SearchableSplitRoute: SearchableSplitRouteWithChildren,
}

const SearchableRouteRouteWithChildren = SearchableRouteRoute._addFileChildren(
  SearchableRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DefaultRouteRoute: DefaultRouteRouteWithChildren,
  SearchableRouteRoute: SearchableRouteRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
